"""Add name fields

Revision ID: 2638e9c8b3a1
Revises: dce8570cb83e
Create Date: 2026-01-16 17:54:30.880339

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2638e9c8b3a1"
down_revision: str | Sequence[str] | None = "dce8570cb83e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("first_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("last_name", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "last_name")
    op.drop_column("contacts", "first_name")
    # ### end Alembic commands ###
